" load pathogen
execute pathogen#infect()

" CtrlP
nnoremap <silent> <Leader>t :CtrlP<CR>
nnoremap <silent> <Leader>b :CtrlPBuffer<CR>
nnoremap <silent> <Leader>c :CtrlPClearCache<CR>

" toggle hlsearch
nnoremap <C-H> :set hlsearch! hlsearch?<CR>

" quick escape
inoremap jj <ESC>

" easier traversal of vim windows
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

" multiple indents without losing highlight
vnoremap < <gv
vnoremap > >gv

" move around huge lines more naturally
nnoremap j gj
nnoremap k gk

" enable project specific vim settings
set exrc
set secure

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smarttab
set copyindent
set laststatus=2
set showmatch
set incsearch
set ruler
set cursorline
set hidden
set nohlsearch
set nu

hi CursorLine term=bold cterm=bold ctermbg=DarkGrey
hi OverLength ctermbg=red ctermfg=white guibg=#592929

match OverLength /\%81v.\+/

" enable language specific settings
syntax on
filetype plugin indent on

" handle related files
au BufRead,BufNewFile *.erb     set filetype=ruby
au BufRead,BufNewFile *.scss    set filetype=css
au BufRead,BufNewFile *.json    set filetype=javascript
au BufRead,BufNewFile *.ctp     set filetype=php

" formatting by filetype
au FileType python,php setlocal ai ts=4 sw=4 sts=4 tw=80 et
au Filetype ruby,yaml,haml,html,sass,javascript,css,sql setlocal ai ts=2 sts=2 sw=2 et

" auto commenting
let maplocalleader = ","
au FileType javascript,c nnoremap <buffer> <localleader>x I//<esc>
au FileType python nnoremap <buffer> <localleader>x I#<esc>


" copy and paste with the system clipboard
set clipboard=unnamed

" retain formatting for text pasted into vim
set paste

set backspace=indent,eol,start
set backupskip=/tmp/*,/private/tmp/*
set stmp

set visualbell
" turn off error bells
set noerrorbells

" history
set history=1000
set undolevels=1000

" turn off swapfiles
set nobackup
set noswapfile

" visualize whitespace
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.

" except for html files
au filetype html,xml set listchars-=tab:>.

set wildmenu
set wildmode=list:longest,full

set splitright
set splitbelow

set hidden

syntax enable
set background=dark

set guifont=Monaco:h16
set guioptions-=T guioptions-=e guioptions-=L guioptions-=r
set shell=bash

augroup vimrc
  autocmd!
  autocmd GuiEnter * set columns=120 lines=70 number
augroup END

if filereadable(expand('~/.vimrc.local'))
  source ~/.vimrc.local
endif
